"""Família de colagem editorial: sobreposição, recorte e folha de contatos."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "editorial-collage"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _overlap(ir: BrandIR) -> LayoutSpec:
    layout_id = "collage-overlap-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Colagem editorial — Planos sobrepostos",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="overlap-primary-mat",
                shape="rectangle",
                area=(62, 188, 576, 650),
                color_token="color.primary",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="overlap-secondary-mat",
                shape="rectangle",
                area=(510, 304, 506, 518),
                color_token="color.primary",
                opacity=0.16,
                z_index=1,
            ),
            ShapeLayer(
                id="overlap-tape-one",
                shape="rectangle",
                area=(140, 154, 184, 34),
                color_token="color.primary",
                opacity=0.5,
                z_index=5,
            ),
            ShapeLayer(
                id="overlap-tape-two",
                shape="rectangle",
                area=(784, 786, 164, 34),
                color_token="color.primary",
                opacity=0.72,
                z_index=5,
            ),
            ShapeLayer(
                id="overlap-copy-field",
                shape="rectangle",
                area=(62, 790, 876, 236),
                color_token="color.background",
                z_index=6,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(62, 76, 480, 36),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=750,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(806, 64, 210, 126),
                fit="fixed",
                font_size_px=108,
                font_weight=850,
                line_height=0.84,
                text_align="right",
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="photo-primary",
                kind="image",
                min_resolution=(1152, 1300),
                area=(62, 188, 576, 650),
                fit="fixed",
                required=False,
                z_index=2,
            ),
            Slot(
                id="photo-secondary",
                kind="image",
                min_resolution=(1012, 1036),
                area=(510, 304, 506, 518),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=34,
                area=(88, 816, 824, 190),
                fit="fixed",
                font_size_px=94,
                font_weight=840,
                line_height=0.88,
                letter_spacing_em=-0.055,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=112,
                area=(520, 1066, 418, 116),
                fit="fixed",
                required=False,
                font_size_px=21,
                line_height=1.2,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(62, 1240, 470, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (884, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["overlap-root"],
            groups=[
                SceneGroup(
                    id="overlap-root",
                    kind="group",
                    area=(0, 0, 1080, 1350),
                    children=["overlap-header", "overlap-images", "overlap-copy", "overlap-footer"],
                ),
                SceneGroup(
                    id="overlap-header",
                    kind="stack",
                    direction="horizontal",
                    gap_px=190,
                    area=(62, 64, 954, 126),
                    children=["kicker", "index"],
                ),
                SceneGroup(
                    id="overlap-images",
                    kind="frame",
                    area=(62, 154, 954, 684),
                    children=[
                        "overlap-primary-mat",
                        "overlap-secondary-mat",
                        "photo-primary",
                        "photo-secondary",
                        "overlap-tape-one",
                        "overlap-tape-two",
                    ],
                ),
                SceneGroup(
                    id="overlap-copy",
                    kind="frame",
                    area=(62, 790, 876, 392),
                    children=["overlap-copy-field", "headline", "body"],
                ),
                SceneGroup(
                    id="overlap-footer",
                    kind="stack",
                    direction="horizontal",
                    gap_px=352,
                    area=(62, 1180, 954, 132),
                    children=["signature", "logo"],
                ),
            ],
        ),
    )


def _cutout(ir: BrandIR) -> LayoutSpec:
    layout_id = "collage-cutout-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Colagem editorial — Recorte circular",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="cutout-disc",
                shape="circle",
                area=(72, 180, 512, 512),
                color_token="color.primary",
                z_index=1,
            ),
            ShapeLayer(
                id="cutout-photo-mat",
                shape="rectangle",
                area=(286, 270, 702, 664),
                color_token="color.primary",
                opacity=0.16,
                z_index=2,
            ),
            ShapeLayer(
                id="cutout-caption-field",
                shape="rectangle",
                area=(650, 834, 338, 100),
                color_token="color.primary",
                z_index=4,
            ),
            ShapeLayer(
                id="cutout-side-rule",
                shape="rectangle",
                area=(72, 754, 8, 422),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="cutout-bottom-rule",
                shape="rectangle",
                area=(72, 1196, 916, 2),
                color_token="color.text",
                opacity=0.28,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                color_token="color.background",
                max_chars=42,
                area=(126, 250, 350, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=750,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=3,
                area=(112, 338, 344, 206),
                fit="fixed",
                font_size_px=178,
                font_weight=850,
                line_height=0.82,
                letter_spacing_em=-0.07,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1404, 1328),
                area=(286, 270, 702, 664),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="caption",
                kind="text",
                role="caption",
                color_token="color.background",
                max_chars=46,
                area=(672, 862, 294, 42),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=700,
                text_align="right",
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=36,
                area=(108, 748, 548, 316),
                fit="fixed",
                font_size_px=102,
                font_weight=860,
                line_height=0.88,
                letter_spacing_em=-0.055,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=112,
                area=(604, 1010, 384, 142),
                fit="fixed",
                required=False,
                font_size_px=22,
                line_height=1.2,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(302, 1234, 424, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="center",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (72, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["cutout-root"],
            groups=[
                SceneGroup(
                    id="cutout-root",
                    kind="frame",
                    area=(0, 0, 1080, 1350),
                    children=["cutout-orbit", "cutout-image", "cutout-message", "cutout-footer"],
                ),
                SceneGroup(
                    id="cutout-orbit",
                    kind="frame",
                    area=(72, 180, 512, 512),
                    children=["cutout-disc", "kicker", "index"],
                ),
                SceneGroup(
                    id="cutout-image",
                    kind="frame",
                    area=(286, 270, 702, 664),
                    children=["cutout-photo-mat", "photo", "cutout-caption-field", "caption"],
                ),
                SceneGroup(
                    id="cutout-message",
                    kind="stack",
                    direction="horizontal",
                    gap_px=56,
                    area=(72, 748, 916, 428),
                    children=["cutout-side-rule", "headline", "body"],
                ),
                SceneGroup(
                    id="cutout-footer",
                    kind="frame",
                    area=(72, 1170, 916, 132),
                    children=["cutout-bottom-rule", "logo", "signature"],
                ),
            ],
        ),
    )


def _contact_sheet(ir: BrandIR) -> LayoutSpec:
    layout_id = "collage-contact-sheet-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Colagem editorial — Folha de contatos",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="contact-frame-one",
                shape="rectangle",
                area=(64, 170, 286, 300),
                color_token="color.primary",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="contact-frame-two",
                shape="rectangle",
                area=(382, 170, 634, 300),
                color_token="color.primary",
                opacity=0.18,
                z_index=1,
            ),
            ShapeLayer(
                id="contact-frame-three",
                shape="rectangle",
                area=(64, 502, 462, 292),
                color_token="color.primary",
                opacity=0.1,
                z_index=1,
            ),
            ShapeLayer(
                id="contact-frame-four",
                shape="rectangle",
                area=(558, 502, 458, 292),
                color_token="color.primary",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="contact-copy-rule",
                shape="rectangle",
                area=(64, 850, 952, 8),
                color_token="color.primary",
                z_index=3,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(64, 72, 474, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=750,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=28,
                area=(706, 72, 310, 34),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.1,
                z_index=10,
            ),
            Slot(
                id="photo-one",
                kind="image",
                min_resolution=(572, 600),
                area=(64, 170, 286, 300),
                fit="fixed",
                required=False,
                z_index=2,
            ),
            Slot(
                id="photo-two",
                kind="image",
                min_resolution=(1268, 600),
                area=(382, 170, 634, 300),
                fit="fixed",
                required=False,
                z_index=2,
            ),
            Slot(
                id="photo-three",
                kind="image",
                min_resolution=(924, 584),
                area=(64, 502, 462, 292),
                fit="fixed",
                required=False,
                z_index=2,
            ),
            Slot(
                id="photo-four",
                kind="image",
                min_resolution=(916, 584),
                area=(558, 502, 458, 292),
                fit="fixed",
                required=False,
                z_index=2,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=36,
                area=(64, 894, 638, 226),
                fit="fixed",
                font_size_px=92,
                font_weight=840,
                line_height=0.89,
                letter_spacing_em=-0.05,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=102,
                area=(756, 906, 260, 178),
                fit="fixed",
                required=False,
                font_size_px=20,
                line_height=1.2,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(64, 1164, 256, 126),
                fit="fixed",
                font_size_px=108,
                font_weight=850,
                line_height=0.84,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(354, 1244, 358, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="center",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (884, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["contact-root"],
            groups=[
                SceneGroup(
                    id="contact-root",
                    kind="grid",
                    columns=2,
                    gap_px=32,
                    area=(64, 72, 952, 1230),
                    children=["contact-header", "contact-images", "contact-copy", "contact-footer"],
                ),
                SceneGroup(
                    id="contact-header",
                    kind="stack",
                    direction="horizontal",
                    gap_px=168,
                    area=(64, 72, 952, 34),
                    children=["kicker", "issue"],
                ),
                SceneGroup(
                    id="contact-images",
                    kind="grid",
                    columns=2,
                    gap_px=32,
                    area=(64, 170, 952, 624),
                    children=[
                        "contact-frame-one",
                        "photo-one",
                        "contact-frame-two",
                        "photo-two",
                        "contact-frame-three",
                        "photo-three",
                        "contact-frame-four",
                        "photo-four",
                    ],
                ),
                SceneGroup(
                    id="contact-copy",
                    kind="frame",
                    area=(64, 850, 952, 270),
                    children=["contact-copy-rule", "headline", "body"],
                ),
                SceneGroup(
                    id="contact-footer",
                    kind="stack",
                    direction="horizontal",
                    gap_px=34,
                    area=(64, 1164, 952, 138),
                    children=["index", "signature", "logo"],
                ),
            ],
        ),
    )


def editorial_collage_package(ir: BrandIR) -> TemplatePackage:
    """Publica três colagens com múltiplas imagens e hierarquia editável."""
    style = derive_style_system(ir)
    layouts = (_overlap(ir), _cutout(ir), _contact_sheet(ir))
    samples = {
        "collage-overlap-post-4x5": {
            "kicker": "Fragmentos de uma ideia",
            "index": "1",
            "headline": "Duas imagens. Uma tensão.",
            "body": "Sobreposições conectam momentos diferentes dentro da mesma narrativa.",
            "signature": "@sua-marca",
        },
        "collage-cutout-post-4x5": {
            "kicker": "Recorte em foco",
            "index": "2",
            "caption": "Detalhe da coleção",
            "headline": "O contexto muda o olhar.",
            "body": "Imagem, círculo e palavra disputam espaço para produzir uma leitura inesperada.",
            "signature": "@sua-marca",
        },
        "collage-contact-sheet-post-4x5": {
            "kicker": "Arquivo em movimento",
            "issue": "Série 01 · 2026",
            "headline": "Uma história em quatro quadros.",
            "body": "A sequência transforma detalhes isolados em um conjunto coerente.",
            "index": "3",
            "signature": "@sua-marca",
        },
    }
    intents = {
        "collage-overlap-post-4x5": (
            "Planos sobrepostos",
            "Criar profundidade pelo choque entre duas imagens, fitas e um campo de texto frontal.",
        ),
        "collage-cutout-post-4x5": (
            "Recorte circular",
            "Fazer imagem, círculo e manchete atravessarem seus limites para formar um novo conjunto.",
        ),
        "collage-contact-sheet-post-4x5": (
            "Folha de contatos",
            "Organizar quatro fragmentos visuais como sequência documental antes da mensagem final.",
        ),
    }
    compositions = []
    for layout in layouts:
        name, intent = intents[layout.id]
        compositions.append(
            TemplateComposition(
                id=layout.id,
                name_pt=name,
                intent_pt=intent,
                layout=layout,
                sample_content_pt=samples[layout.id],
                critical_nodes=["headline", "logo"],
                export_support=ExportSupport(pptx="native"),
            )
        )
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Colagem editorial",
        title_pt="Colagem editorial",
        description_pt=(
            "Três composições editáveis para narrativas com recortes, sobreposição e múltiplas imagens."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
